[package]
name = "ToDo_backend"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = "0.8.7"
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
